Track first app launches
Automattic/studio pull request #284
Opened 2024-06-21 08:45 UTC by jeroenpf

Related to: https://github.com/Automattic/dotcom-forge/issues/7578

We want to track first-time launches of the app. This was already implemented but due to the name of the stat being too long, it was not tracked.

## Proposed Changes

- Remove the `-first` stat that is automatically sent on aggregated bumps in favor of explicitly logging first-time events when needed.
- When no `lastBumpStats` have been set in the userdata, assume it is the first time the app was launched and bump the stat. 

## Testing Instructions

To test that the stat bump is sent successfully, you can monitor the log output of `npm run start`. We need to emulate a first-launch so we need to temporarily remove/move the `appdata-v1.json` file.

- Move your `appdata-v1.json` file somewhere safe.
- Run `npm run start`
- Observe that the stats are sent by verifying that the following is logged:
   - `Would have bumped stat: studio-app-launch-first=darwin`
   - `Would have bumped stat: studio-app-launch-total=darwin`
   - `Would have bumped stat: local-environment-launch-uniques=darwin`
 - Stop the npm run process and start it again. This time observe that only `Would have bumped stat: studio-app-launch-total=darwin` is visible in the logs.

## Pre-merge Checklist

- [ ] Have you checked for TypeScript, React or other console errors?

2024-06-21 14:03 UTC, kozer approved these changes
Tested it and work as expected! Nice work @jeroenpf !
![image](https://github.com/Automattic/studio/assets/497103/df899fc3-f86e-4ac5-b544-df21907ed55a)

2024-06-21 14:09 UTC, kozer requested changes
I realized that the `local-environment-launch-uniques` didn't dispatched, as if you notice in the screenshot there is an error saving the file.
We had this problem before, but I had many weeks to encounter it.

I'm not approving yet, as we need to test it more ( I deleted the json file and tried to replicate 4-5 times without success )

2024-06-21 14:23 UTC, wojtekn approved these changes
The code changes look good, works as expected. Thanks for making the code easier to read.

@kozer is the issue occurring when you delete JSON related to changes from this PR?

2024-06-26 12:21 UTC, kozer approved these changes
Didn't happen again, so I'm approving.

2024-06-26 13:45 UTC, merged